'use client'

import './globals.css'
// import { UserProvider } from '@/providers/user-provider'
import { Provider } from 'react-redux'
import store from './store'
import { ThemeProvider } from '../providers/theme-provider'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Provider store={store}>
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </Provider>
    </html>
  )
}
