apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamwizard-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streamwizard-frontend
  template:
    metadata:
      labels:
        app: streamwizard-frontend
    spec:
      containers:
      - name: streamwizard-frontend
        image: ghcr.io/streamerbuddybot/test:e5aa8d96c72c6a8f1681bd07a3a8b4dc4f029e13
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: streamwizard-frontend