apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamwizard-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streamwizard-frontend
  template:
    metadata:
      labels:
        app: streamwizard-frontend
    spec:
      containers:
      - name: streamwizard-frontend
        image: ghcr.io/streamerbuddybot/test:2b54bece49f5982c958376a8e16a65e2ef675f24
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: streamwizard-frontend