resources:
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app: streamwizard-frontend

commonAnnotations:
  app: streamwizard-frontend-annontations

namePrefix:
  kustom-

nameSuffix:
  -v1