name: Update Package.json Version and Build/Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  update-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Update IMAGE Version
        run: |
          sed -i "s|image: ghcr.io/${{ github.repository }}:.*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|" kubernetes/resources/deployment.yaml
      
      

      - name: push updated deployment.yaml
        run: |
          git config --global user.email "jochem1111@gmail.com"
          git config --global user.name "Jochemwhite(github actions))"
          git add kubernetes/resources/deployment.yaml
          git commit -m "Update deployment.yaml"
          git push

      - name: Build
        run: |
          docker build .

   


    
        



            